version: 0.2

phases:
  install: 
    commands:
      - npm install -g snyk
      - snyk auth $SNYK_TOKEN
      - snyk test
      - snyk code test
      - snyk monitor
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
artifacts:
  files:
    - target/dvja-1.0-SNAPSHOT.war